# Домашнє завдання 03. Основи статистики для аналізу даних

In [25]:
import pandas as pd
import numpy as np

In [26]:
california_housing_df = pd.read_csv('https://raw.githubusercontent.com/dmitriy-shtefan/python-ai/main/data/california_housing.csv')
california_housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

3. Для 3-5 числових колонок з датасета порахувати mean, median, mode, variance, std. Обов'язково включити MedHouseVal і ще мінімум 2 ознаки, наприклад MedInc, HouseAge, AveRooms, Population, AveOccup.

In [27]:
california_housing_df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010


* MedInc      Медіанний дохід
* HouseAge	Медіанний вік будинку
* AveRooms	Середня кількість кімнат
* AveBedrms	Середня кількість спалень
* Population	Населення
* AveOccup	Середня кількість мешканців
* Latitude	Широта
* Longitude	Довгота
* MedHouseVal	Медіанна вартість житла

In [28]:
california_housing_df.mode()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,3.1250,52.0,5.0,1.0,891.0,3.0,34.06,-118.31,5.00001
1,15.0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Variance (дисперсія) - це std в квадраті

In [29]:
california_housing_df.var()

MedInc         3.609323e+00
HouseAge       1.583963e+02
AveRooms       6.121533e+00
AveBedrms      2.245915e-01
Population     1.282470e+06
AveOccup       1.078700e+02
Latitude       4.562293e+00
Longitude      4.014139e+00
MedHouseVal    1.331615e+00
dtype: float64

4. Знайти мінімум 3 пари ознак і порахувати кореляцію між ними. Серед цих пар має бути мінімум 2 пари з цільовою змінною MedHouseVal, наприклад MedInc і MedHouseVal, AveRooms і MedHouseVal.

In [30]:
r = california_housing_df['MedInc'].corr(california_housing_df['MedHouseVal']) 
print(r)

0.6880752079585478

0.6880752079585478  - показник вказує на середній зв'язок  (0,5 - 0,7 => середній )

In [31]:
r = california_housing_df['AveRooms'].corr(california_housing_df['MedHouseVal'])
print(r)

0.15194828974145785

0.15194828974145785 - слабкий зв'язок або його зовсім немає (< 0.3)

In [32]:
r = california_housing_df['MedInc'].corr(california_housing_df['AveRooms'])
print(r)

0.3268954316412956

0.3268954316412956 - помірний зв'язок (0,3 - 0,5 - помірний)

In [33]:
r = california_housing_df['AveRooms'].corr(california_housing_df['MedHouseVal'])
print(r)

0.15194828974145785

In [34]:
r = california_housing_df['HouseAge'].corr(california_housing_df['MedInc'])
print(r)

-0.11903398993785663

-0.11903398993785663  - відсутній будь-який зв'язок

In [35]:
r = california_housing_df['Population'].corr(california_housing_df['AveOccup'])
print(r)

0.06986273036567671

0.06986273036567671 відсутній зв'язок

In [36]:
r = california_housing_df['Latitude'].corr(california_housing_df['Longitude'])
print(r)

-0.9246644339150404

-0.9246644339150404 відсутній зв'язок

In [37]:
r = california_housing_df['AveRooms'].corr(california_housing_df['AveBedrms'])
print(r)

0.8476213257130447

0.8476213257130447 - сильний зв'язок (> 0.7)

In [38]:
r = california_housing_df['MedHouseVal'].corr(california_housing_df['Population'])
print(r)

-0.02464967888889488

In [39]:
r = california_housing_df['MedHouseVal'].corr(california_housing_df['HouseAge'])
print(r)

0.10562341249320992

5. Пояснити, які ознаки мають потенційно корисний зв'язок із MedHouseVal, а які зв'язки виглядають слабкими або неочевидними.

Серед проведених кореляцій:
* помірний зв'язок відмічено при кореляції MedInc - AveRooms = 0,3 - тобто чим вищий середній дохід, тим більша середян кількість кімнат;
 * потенційно корисний зв'язок виявився у MedInc - MedHouseVal - має середній кореляційний зв'язок = 0,6, що свідчить про те чим вищий  середній дохід, тим вище буде вартість житла. 
 * Досить важливий  виявився зв'язок AveRooms - AveBedrms, який складає 0,8 - сильний кореляційний зв'язок. Напевно, це говорить про покращені умови проживання, кофорт і чітко пов'язуєтьсяя з попереднім показником, що можна описати логічним ланцюгом ==> дохід - платоспроможність - більша кількість кімнат = більша площа (комфорт) - ціни на житло.
    * Всі інші показники мали досить низький кореляційний зв'язок або він взагалі був відсутній - такі ознаки не будуть цінними або корисними.

6. Окремо описати одну колонку з california_housing, де середнє і медіана суттєво відрізняються. Пояснити, що це може означати.

In [40]:
california_housing_df.mean() < california_housing_df.median()

MedInc         False
HouseAge        True
AveRooms       False
AveBedrms      False
Population     False
AveOccup       False
Latitude       False
Longitude       True
MedHouseVal    False
dtype: bool

In [41]:
california_housing_df.mean() > california_housing_df.median()

MedInc          True
HouseAge       False
AveRooms        True
AveBedrms       True
Population      True
AveOccup        True
Latitude        True
Longitude      False
MedHouseVal     True
dtype: bool

In [42]:
california_housing_df.mean() - california_housing_df.median()

MedInc           0.335871
HouseAge        -0.360514
AveRooms         0.199871
AveBedrms        0.047895
Population     259.476744
AveOccup         0.252540
Latitude         1.371861
Longitude       -1.079704
MedHouseVal      0.271558
dtype: float64

* В кожному із стовпців по даним показникам: mean і mediana, наявна асиметрія, більшою міро, по правому плечу. Різниця незначна, але присутня,  що свідчить про наявність одиничник випадків де є будинки з підвищеним комфортом, які в свою чергу коштують дорожче в порівняянні з середньою ринковою ціною. 
* найбільша різниця в колонці Population, що свідчить про наявність одного або декілька районів з дуже  великою кількісю насення, тому така різниця в занченнях 

* дві колонки мають негативне значення - лівосторнню асиметрію: HouseAge + Longitude, що свідчить про наявність дуже старих будинків та будівель на певній широті, на відміну від загального житлового фонду. Можливо це особливість району і вже перевага під час продажу нерухомості. Варто дослідити подібні викиди більш детально.

7. Зробити короткий підсумок: які 1-2 ознаки, на вашу думку, найкраще допомагають пояснити вартість житла в цьому датасеті.

* MedInc 
* AveBedrms
* AveRooms
Підтверджується кореляційним зв'язками.

Можна описати логічним ланцюгом ==> дохід - платоспроможність - більша кількість кімнат = більша площа (комфорт) - ціни на житло.


біль детально надана відповідь у питанні №5